### ISSUE TITLE
Unfortunately, Hello Cordova (CLI) has stopped

### ISSUE THREAD

**Issue by tanzeelrana** [xmnboy/hello-cordova#1] opened 2015-04-25 07:41 UTC
I clone the repo 
cd into the directory 
->cordova platform add android
->cordova build
->cordova run android

the app installs successfully

but I get this message "Unfortunately, Hello Cordova (CLI) has stopped" 

am I missing something ?

**Comment by xmnboy** [comment] 2015-04-26 00:19
The app has not been tested with Cordova CLI since the CLI 3.5 release, so I'm not sure what you might be seeing in that error message. My dev machine had some difficulties recently as a result of an update to Yosemite, so it will take me a while to check into using this project with the most recent edition of CLI (which has incorporated many significant changes that may be the cause of the troubles). 

One thing to note, you do need to install the required plugins for the app in order to make it work with CLI. I recommend you try out the app first with the Intel XDK if you want to see what it does and how it works, that will be much simpler. When time permits I'll update my Cordova CLI and confirm if the app builds properly in the new CLI environment.

**Comment by xmnboy** [comment] 2017-12-04 23:59
Closing this issue since Cordova CLI 3.5 no longer applies; this app has been updated significantly since that release and has only been tested against CLI versions 5.x and 6.x.

**Closed as completed by xmnboy** 2017-12-04 23:59 UTC
